### ISSUE TITLE
Configurations extraction

### ISSUE THREAD

**Issue by ssirag** [HealthITAU/pyconnectwise#23]
I'm trying to use the library to export the full list of active configs, but I'm only getting a subset.  How can I get a complete dump of all configurations for a specified company?

**Comment by ssirag** [comment]
I've reviewed the pageSize limits referenced, but even with pageSize 1000 I only get 25 items at a time.

**Comment by EMoonArchiTech** [comment]
Hi ssirag, I've managed to do this for my own environment with no issue. Can you share the section of the code you're using to pull the CI's?

```python
manage_api_client = ConnectWiseManageAPIClient(...)

config_search: = manage_api_client.company.configurations.paginated(1, 1000)

# and then later iterate through items in those pages like so:

config_list = []
for config in config_search.all():
    config_list.append(config)
```

**Comment by Yoshify** [comment]
Unfortunately I am also unable to replicate this issue - @ssirag, could you perhaps share your code or some information about your environment?

**Comment by EMoonArchiTech** [comment]
Maybe we should close this one off for inactivity?
